# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Practitioner.destroy_all
User.destroy_all
UserPractitioner.destroy_all

pract1 = Practitioner.create(name: "Laura Luna, LICSW", specialties: ["Cultural Identity", "Family Conflict", "Parenting"], about: "I am an experienced therapist who works with children, adolescents, adults and couples. I provide treatment for a variety of issues, including: depression, anxiety, relationship issues, life transitions, and trauma. Through the use of evidence-based interventions including, Cognitive Behavioral Therapy, Emotionally Focused Therapy and play therapy techniques I help client identify their triggers, and learn healthier ways to manage their emotions and deal with life stressors.
I believe in focusing on the unique strengths that each individual possesses and how those strengths can help them in overcoming their challenges. I also believe that the therapeutic relationship between therapist and client is an important factor in the success of therapy and strive to create a safe and understanding therapeutic environment.
I am a bi-cultural and bilingual therapist, and enjoy working with people of all backgrounds and ethnicities. Though my office is located in Washington D.C, I am licensed in DC and Virginia, and can offer tele-therapy to people located in Virginia who may prefer this method of communication due to their schedules.", zip_code: 20016 , image:"https://latinxtherapy.com/wp-content/uploads/listing-uploads/gallery/2020/09/profile-picture.jpg", languages: ["English", "Spanish"])

Practitioner.create(name: "Dr. Jacqueline Guevara, LCSW", specialties: ["Addictions", "Alcohol abuse", "Trauma and PTSD"], about: "'You may encounter many defeats, but you must not be defeated' - Maya Angelou. I am a true believer that no matter how heavy a situation, la esperanza (hope) can see you through. As a clinician, my job is to help you get your life back while creating a safe space for you to grow and feel that hope. As a first generation Guatemalteca and Salvadoreña, I understand the struggles you may have come across as a Latinx person navigating systemic oppression and carrying the pain of racial trauma. I also work with you to not only help you understand your depression, anxiety, drug abuse, or daily stress, but to also manage it effectively. This healing journey won't be easy, but in working together we can tap into your greatest potential and help you live the life you deserve. Visit my website to learn more or to schedule your appointment!", zip_code: 20017 , image:"https://latinxtherapy.com/wp-content/uploads/listing-uploads/logo/2020/08/TinaHeadshots1of22-Cropped-Rec.jpg", languages: ["English", "Spanish"])

Practitioner.create(name: "Christopher Straley LICSW", specialties: ["Gay", "Sex Therapy", "Relationship Issues"], about: "With over 20 years of experience providing mental health services, primarily to men, individuals and couples, who are struggling with relationship issues, sexual health, and/or substance use issues, my focus is on helping you feel better. If you are struggling to feel connected with your partner, or others in your life, therapy can help. As a relationship specialist and sex therapist, I work with you, to help understand and improve communication, heal past ruptures, and increase intimacy - emotional and sexual. We may also work together to decrease your sexual performance anxiety, increase confidence, and pleasure.
I also work with men struggling with Out of Control Sexual Behavior, and/or substance use. You and I work together to identify what you feel is problematic about your behaviors and then work together to reach your goals.
I offer clinical consultation to other clinicians, and am Certified as a Maryland Social Work Supervisor. I am also a Certified Group Psychotherapist (by American Group Psychotherapy Association), and a Certified Sex Therapist (by the American Association of Sexuality Educators, Counselors and Therapists).", zip_code: 20008 , image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/27/93/49327-851702-3_320x400.jpg?pu=1524534448", languages: ["English"])

Practitioner.create(name: "Ronald O Esquivel LPC", specialties:["Gay", "Marital and Premarital", "Men's Issues"], about: "I am a Licensed Professional Counselor in the District of Columbia. My goal is to support you in capitalizing on your strengths in order to experience life to the fullest. I understand that creating growth requires emotional resilience, and is a life-long commitment. Working with individuals in creating new perspectives, and with couples in creating shared meaning is my commitment to you. Let me embark in this journey with you, so that you too, can create a new narrative.
I thrive in providing support to individuals and couples using a holistic and emotion-focused approach, exploring the contributions of race, class, age, gender and sexual orientation to the development of self, career, and relationships. In my work, I also explore the influence of society in self esteem and self worth.
As a gay male therapist with focused experience working with members of the LGBTQ+ community, I strive to support you in understanding your strengths and work on unique and identified issues encountered by people in our community, issues such as body image/self-esteem, coming out, sexual/gender identity, micro-aggressions, and interpersonal relationships.", zip_code: 20009, image:"https://cdn0.sussexdirectories.com/rms/rms_photos/sized/24/05/390524-1834917-3_320x400.jpg?pu=1588801580", languages: ["English", "Spanish"])

Practitioner.create(name: "Molly Byrom LCSW", specialties:["Gay", "Anxiety", "Depression"], about: "As a therapist, I am committed to providing clients with a warm, non-judgmental environment. Clients are the experts of their own lives, and I want to guide them to identify and practice new ways of living. I work with individuals to include children, teens and adults. I have a passion for working with the LGBTQIA+ population, and/or people who are navigating faith and spirituality.
I specialize in LGBTQ issues, anxiety, depression, self-esteem and relationship conflict. My certifications are in CBT and DBT, and I use systems theory to guide my practice. With a cultural humility approach, I do not claim to be an expert, but I commit to being sensitive to the experiences of others.
Relationships challenges and life obstacles can be tough, but reaching out for help is a great first step! I'm here to help you navigate conflict, and heal through self love and acceptance", zip_code: 20001, image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/37/98/789837-1950974-2_320x400.jpg?pu=1599746342", languages: ["English"])

Practitioner.create(name: "Dr. Elizabeth Amerson Licensed PhD", specialties:["Behavioral health", "Childhood trauma", "Testing and Evaluation"], about: "Licensed psychologist concerned for individuals experiencing problems with attention, concentration, memory, and learning (which often goes along with some anxiety and depression). Effective treatment begins with an accurate diagnosis. I provide psychological testing and assessment for all cultural groups to secure accurate diagnosis. This service includes a comprehensive report, including recommendations and accommodations for academic success. I also provide psychotherapy to help clients improve quality of life and to reach personal goals. I'm a member of the National Register of Health Service Psychologists, and a clinician with the National Health Service Corps. I have been a clinician and healthcare leader in inpatient, outpatient, academic and research settings. In addition to testing and assessment, I provide psychotherapy utilizing cognitive-behavioral and client-centered perspectives.", zip_code: 21044, image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/30/42/274230-550293-3_320x400.jpg?pu=1454686030", languages: ["English"])

Practitioner.create(name: "Alexis A. Moreno PsyD", specialties:["Relationship Issues", "Life Coaching", "Trauma & PTSD", "Sexual Identity"], about: "I have experience providing sexual health & relationship workshops, psychotherapy with children, families, & couples recovering from violence and trauma, & I have treated adults involved in the criminal justice system suffering with severe mental illness. My diverse training & practice allows me to provide you unconditionally positive & supportive services. I love and truly believe in everyone's potential. Working on yourself alone can be incredibly challenging. I am here to collaborate with you and support you through your goals and aspirations.", zip_code: 20001, image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/42/91/369142-1130463-2_320x400.jpg?pu=1512659108", languages: ["English", "Spanish"])

Practitioner.create(name: "Michell K. Stanley LCSW", specialties:["Career Counseling", "Relationship Issues", "Racial Identity"], about: "I use psychotherapy to alleviate symptoms of emotional distress (such as anxiety or depression). I use life coaching to maximize personal and professional potential towards the results you want for your future. I help my clients to gain more fulfillment by empowering them to develop intuition and insight through cultivating healthy lifestyle habits. My mission is to help people use emotional challenges as opportunities for self-growth and evolution. My holistic approach shows people how to get more Balance, Intimacy, and Trust in themselves and in their lives in order to thrive in the present and secure their legacy. I offer a program of services to my client that combines life coaching and psychotherapy. This structure supports client's in being accountable to developing the path of their most fulfilled life, while empowering them to expand growth after our work is over.", zip_code: 20904 , image:"https://cdn0.sussexdirectories.com/rms/rms_photos/sized/49/78/67849-378174-2_320x400.jpg?pu=1428500738", languages: ["English"])

Practitioner.create(name: "Eduardo Cortina LPC", specialties:["Emotional Disturbance", "Sexual Abuse", "Anxiety, Men’s Issues"], about: "Are you suffering from the effects of PTSD, anxiety, depression, sudden loss, and/or chronic pain? If so body-oriented psychotherapy may help facilitate your recovery. By working to address the root causes of nervous system imbalance, a body-psychotherapy approach can empower the client with tools and skills to re-negotiate and resolve difficult and traumatic experiences. My approach in therapy is client-centered and my work is just to facilitate and provide the optimal conditions for healing to take place. I also hope to impart knowledge and skills for people to work with themselves effectively outside of therapy. Scientific research supports including body-based mindfulness and body based practices to treat trauma. If you have questions or may be interested in this approach, please feel free to contact me. In addition to being a psychotherapist, I have worked as a body worker, massage, and movement therapist for the last 20 years.", zip_code: 20016, image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/01/24/272401-1148958-3_320x400.jpg?pu=1516077142", languages: ["English", "Spanish"])

Practitioner.create(name: "Kathy Nguyen Li, Clinical Psychologist", specialties:["Anxiety", "Depression", "Women’s Issues"], about: "I have 14+ years of experience working w/ clients from diverse backgrounds. I specialize in working w/ anxiety, depression, identity and multicultural issues, and relationship difficulties. I am a Certified EFT couples therapist, where we focus on improving communication and emotional closeness. At the end of counseling, my clients often express having improved mood, reduced anxiety, more confidence, better coping skills, and a greater sense of control over their lives and relationships. My approach is nonjudgmental and collaborative. Clients tell me I am warm, genuine, and easy to talk to, but I am also active, ask good questions, and can gently challenge too when it may helpful. I believe in working towards greater understanding of ourselves and meaningful and lasting change. I strive to practice with cultural competence and humility.", zip_code: 20036, image:"https://cdn0.sussexdirectories.com/rms/rms_photos/sized/64/42/114264-327510-3_320x400.jpg?pu=1414181693", languages: ["English", "Vietnamese"])
Practitioner.create(name: "Jamaal A. Crone LPC", specialties:["Gay", "Depression", "Relationship Issues"], about: "If you are seeking to enhance your life by building connection, confidence, character, and community, I invite you to contact me so we can begin the journey together. I work primarily from a Cognitive-Behavioral approach, which is a short-term, results-oriented method. Integrating Acceptance and Commitment Therapy, I support my clients with becoming who they desire to be. These evidence-based treatments are especially effective for depression and anxiety.
My passion and specialty for working with couples draws from Emotionally Focused Couples Therapy. EFT is a highly researched form of couples counseling proven to have excellent results. I create a supportive environment for exploring communication differences, betrayal, and hurt; experiences I have also had as a married man.
I've researched Trauma-Informed Clinical Pastoral Care and provided trainings for multiple organizations on factors impacting mental health of the LGBTQ+ community. In our sessions you'll find me interactive, relaxed and intentional about our therapeutic relationship. Oh and don't be surprised we will laugh along the way!", zip_code: 20009, image:"https://cdn2.sussexdirectories.com/rms/rms_photos/sized/50/34/343450-1892417-3_320x400.jpg?pu=1594411907", languages: ["English"])

Practitioner.create(name: "Eric Jones Psychologist, PhD", specialties:["Emotional disturbance", "Relationship Issues", "Men’s Issues"], about: "The conflict for you is that you are talented and capable, but underneath you are not so sure. You have overcome challenges and survived. Yet there remains self-doubt and anxiety. You are not going to get to where you feel you should be as long as these struggles weigh you down. Are you feeling misunderstood by others or unsure who's right for you? Or maybe unsure of what you really need? Whatever the reasons, it leads you to a familiar road of dissatisfaction, frustration, and sadness.
You have more strength than you realize and your resiliency has brought you far. However, you are locked in patterns of thinking and behavior that doesn't allow you to feel your own worth and power. My goal is to target, challenge, and redirect the thinking that keeps you stuck so that you begin feeling genuine satisfaction. This journey can be done.
I specialize in working with adolescents and adults. As I use a cultural lens in my work, I welcome communities of color, LGBTQ individuals and those who have felt marginalized. Let's get started!", zip_code: 20006, image:"https://cdn4.sussexdirectories.com/rms/rms_photos/sized/94/86/738694-1908430-3_320x400.jpg?pu=1596142584", languages: ["English"])

user1 = User.create(name: "Edward Cullin", email: "his@email.com")

UserPractitioner.create(user_id: user1.id, practitioner_id: pract1.id, reviews: "Dr gave me all the information with knowledgeable response and precaution I need to take for future safety.", likes: 1)